plugins {
	id 'java-library'
	id "com.vanniktech.maven.publish" version "0.32.0"
}

group = 'io.github.clean-code0244'

version = '3.0.6'

java {
	sourceCompatibility = '25'
}

repositories {
	mavenCentral()
}

ext {
	springVersion = '7.0.2'
	jacksonVersion = '2.21.0'
	slf4jVersion = '2.0.16'
	jakartaAnnotationVersion = '3.0.0'
	lombokVersion = '1.18.42'
	jakartaWsRsVersion = '4.0.0'
}

dependencies {

	api "jakarta.ws.rs:jakarta.ws.rs-api:${jakartaWsRsVersion}"

	implementation "org.springframework:spring-web:${springVersion}"
	implementation "org.springframework:spring-context:${springVersion}"

	implementation "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
	implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
	implementation "org.slf4j:slf4j-api:${slf4jVersion}"

	compileOnly "org.projectlombok:lombok:${lombokVersion}"
	annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

	testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
	testImplementation "org.springframework:spring-test:${springVersion}"
	testImplementation 'org.mockito:mockito-core:5.14.2'
}

tasks.named('jar') {
	enabled = true
	archiveClassifier.set('')
}

import com.vanniktech.maven.publish.SonatypeHost

mavenPublishing {
	coordinates("io.github.clean-code0244", "adts-secret-manager", version)

	pom {
		name = "ADTS Secret Manager"
		description = "Spring Framework library for CyberArk Conjur integration (Universal)"
		url = "https://github.com/Clean-Code0244/adts-secret-manager"
		inceptionYear = "2024"

		licenses {
			license {
				name = "The Apache License, Version 2.0"
				url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
				distribution = "repo"
			}
		}

		developers {
			developer {
				id = "Clean-Code0244"
				name = "Clean-Code0244"
				email = "tursunyusufomer@gmail.com"
			}
		}

		scm {
			url = "https://github.com/Clean-Code0244/adts-secret-manager"
			connection = "scm:git:git://github.com/Clean-Code0244/adts-secret-manager.git"
			developerConnection = "scm:git:ssh://github.com/Clean-Code0244/adts-secret-manager.git"
		}
	}

	publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)

	signAllPublications()
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(GenerateModuleMetadata).configureEach {
	enabled = false
}